// Generated by pipeline/scripts/build_hero_wall.py — do not edit.
//
// The landing page's hero is one image per orientation, not a grid of
// sixty. Sixty tiles meant 25 requests before a phone had any hero at
// all, repeated on every visit; a single sheet either arrives or does
// not, and the hash in the filename lets it be cached immutable.
//
// Re-run pipeline/scripts/build_hero_images.py to refresh from recent
// scans, or build_hero_wall.py to recompose from the tiles on disk.
export const HERO_WALL = {
  portrait: {
    webp: "/hero/wall-portrait.e1915b56.webp",
    jpg: "/hero/wall-portrait.ecc1fcd6.jpg",
    columns: 6,
    rows: 10,
  },
  landscape: {
    webp: "/hero/wall-landscape.e993a7fb.webp",
    jpg: "/hero/wall-landscape.b3fdb141.jpg",
    columns: 12,
    rows: 5,
  },
  tiles: 60,
} as const;
