-- Indigenous Scraper — database schema
-- Paste this into the Supabase SQL editor and click Run.
-- Safe to re-run: drops are commented out for safety.

-- ----------------------------------------------------------------------
-- Extensions
-- ----------------------------------------------------------------------
create extension if not exists vector;       -- CLIP embeddings
create extension if not exists pgcrypto;     -- gen_random_uuid()


-- ----------------------------------------------------------------------
-- Tribes — top 50 federally recognized tribes (seeded from BIA list)
-- ----------------------------------------------------------------------
create table if not exists tribes (
  id                   uuid primary key default gen_random_uuid(),
  name                 text not null unique,
  canonical_name       text not null,
  rank                 int,                       -- 1..50 by approximate enrollment
  has_registered_mark  boolean default false,
  uspto_status         text,                      -- 'registered' | 'unknown' | 'pending'
  uspto_notes          text,
  uspto_search_url     text,
  created_at           timestamptz not null default now()
);

create index if not exists idx_tribes_rank on tribes(rank);


-- ----------------------------------------------------------------------
-- Reference assets — each tribe's official seal/flag images
-- ----------------------------------------------------------------------
create table if not exists reference_assets (
  id           uuid primary key default gen_random_uuid(),
  tribe_id     uuid not null references tribes(id) on delete cascade,
  asset_type   text not null,                     -- 'seal' | 'flag' | 'logo'
  description  text not null,                     -- e.g. "Cherokee Nation seal"
  image_url    text not null,                     -- Supabase Storage URL or external
  source_url   text,                              -- where the asset was sourced from
  embedding    vector(512),                       -- CLIP ViT-B/32 embedding
  created_at   timestamptz not null default now()
);

create index if not exists idx_reference_assets_tribe on reference_assets(tribe_id);


-- ----------------------------------------------------------------------
-- Listings — scraped products from Amazon, Alibaba, etc.
-- ----------------------------------------------------------------------
create table if not exists listings (
  id                uuid primary key default gen_random_uuid(),
  tribe_id          uuid not null references tribes(id) on delete cascade,
  marketplace       text not null,                -- 'amazon' | 'alibaba'
  marketplace_id    text,                         -- ASIN / Alibaba product id
  title             text not null,
  seller            text,
  price             text,                         -- keep as text — currencies vary
  listing_url       text not null,
  image_url         text,
  image_embedding   vector(512),                  -- cached for re-matching
  search_query      text,                         -- what we typed to find it
  scraped_at        timestamptz not null default now(),
  unique (marketplace, marketplace_id)
);

create index if not exists idx_listings_tribe on listings(tribe_id);
create index if not exists idx_listings_marketplace on listings(marketplace);


-- ----------------------------------------------------------------------
-- Matches — listings linked to reference assets with a confidence score
-- This is the core of the review queue.
-- ----------------------------------------------------------------------
create table if not exists matches (
  id                  uuid primary key default gen_random_uuid(),
  listing_id          uuid not null references listings(id) on delete cascade,
  reference_asset_id  uuid not null references reference_assets(id) on delete cascade,
  confidence          numeric(4,3) not null,      -- 0.000–1.000
  confidence_band     text not null,              -- 'low' | 'medium' | 'high'
  status              text not null default 'awaiting_review',
                      -- 'awaiting_review' | 'confirmed' | 'dismissed'
  reviewed_at         timestamptz,
  created_at          timestamptz not null default now(),
  unique (listing_id, reference_asset_id)
);

create index if not exists idx_matches_status on matches(status);
create index if not exists idx_matches_confidence on matches(confidence desc);


-- ----------------------------------------------------------------------
-- Takedown drafts — generated by Claude for human review before sending
-- ----------------------------------------------------------------------
create table if not exists takedown_drafts (
  id           uuid primary key default gen_random_uuid(),
  match_id     uuid not null references matches(id) on delete cascade,
  draft_type   text not null,                     -- 'marketplace_takedown' | 'ag_notification'
  recipient    text,                              -- 'amazon' | 'alibaba' | 'ok_ag' etc.
  body         text not null,
  status       text not null default 'draft',     -- 'draft' | 'sent' | 'removed'
  sent_at      timestamptz,
  created_at   timestamptz not null default now()
);

create index if not exists idx_drafts_match on takedown_drafts(match_id);
create index if not exists idx_drafts_status on takedown_drafts(status);


-- ----------------------------------------------------------------------
-- Dashboard summary view (powers the four header counters)
-- ----------------------------------------------------------------------
create or replace view tribe_summary as
select
  t.id                                                              as tribe_id,
  t.name                                                            as tribe_name,
  count(distinct m.id)                                              as listings_flagged,
  count(distinct m.id) filter (where m.status = 'awaiting_review')  as awaiting_review,
  count(distinct d.id) filter (where d.status = 'sent')             as notices_sent,
  count(distinct d.id) filter (where d.status = 'removed')          as removed
from tribes t
left join reference_assets ra on ra.tribe_id = t.id
left join matches m           on m.reference_asset_id = ra.id
left join takedown_drafts d   on d.match_id = m.id
group by t.id, t.name;
