"""
Copy the landing page's hero tiles into the repo, resized.

The hero hotlinked 25-60 thumbnails straight from m.media-amazon.com. That is
25 third-party requests on first paint: the last one landed 6.1s in over LTE,
the top rows were still arriving when the page looked finished, and a delisted
product breaks its tile for good. None of that is worth it for imagery that is
decorative.

Served from public/hero/ they are same-origin, on Vercel's CDN with the page,
cached, and sized for the ~78-107px they actually render at instead of shipping
320px thumbnails.

The trade is that the wall becomes a periodic refresh rather than always
current. Re-run this whenever you want it to reflect recent scans:

    python3 -m scripts.build_hero_images

Writes public/hero/*.jpg and src/lib/heroImages.ts.
"""

import io
import os
import sys

import requests
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.db import get_client  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_DIR = os.path.join(ROOT, "public", "hero")
MANIFEST = os.path.join(ROOT, "src", "lib", "heroImages.ts")

# Desktop lays out 12 columns and shows about 60; phones show 25.
TILE_COUNT = 60
# Tiles render at 78px (phone) to 107px (desktop). 260 covers 3x on the phone
# and 2x on desktop with room to spare.
MAX_EDGE = 260
QUALITY = 78
UA = "OnlineProvenance/1.0 (+https://onlineprovenance.vercel.app)"


def main() -> int:
    client = get_client()
    rows = (
        client.table("tribes")
        .select("name, listings(id, image_url)")
        .execute()
        .data
    )

    # Round-robin across nations, exactly as the page did, so the wall shows
    # many nations rather than sixty listings from one.
    per_tribe = []
    for t in rows:
        imgs = [l["image_url"] for l in (t.get("listings") or []) if l.get("image_url")]
        if imgs:
            per_tribe.append(imgs)

    picked: list[str] = []
    seen: set[str] = set()
    for i in range(40):
        for imgs in per_tribe:
            if len(picked) >= TILE_COUNT:
                break
            if i < len(imgs) and imgs[i] not in seen:
                seen.add(imgs[i])
                picked.append(imgs[i])
        if len(picked) >= TILE_COUNT:
            break

    print(f"{len(per_tribe)} nations with photos; taking {len(picked)} tiles\n")
    os.makedirs(OUT_DIR, exist_ok=True)
    for old in os.listdir(OUT_DIR):
        if old.endswith(".jpg"):
            os.remove(os.path.join(OUT_DIR, old))

    saved: list[str] = []
    total = 0
    for idx, url in enumerate(picked, start=1):
        name = f"hero-{idx:02d}.jpg"
        try:
            resp = requests.get(url, headers={"User-Agent": UA}, timeout=30)
            resp.raise_for_status()
            im = Image.open(io.BytesIO(resp.content))
            im = im.convert("RGB")
            im.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)
            path = os.path.join(OUT_DIR, name)
            im.save(path, "JPEG", quality=QUALITY, optimize=True, progressive=True)
            size = os.path.getsize(path)
            total += size
            saved.append(name)
            print(f"  {name}  {im.width}x{im.height}  {size/1024:5.1f}KB")
        except Exception as e:  # noqa: BLE001
            print(f"  SKIP {name}: {str(e)[:70]}")

    with open(MANIFEST, "w") as fh:
        fh.write(
            "// Generated by pipeline/scripts/build_hero_images.py — do not edit.\n"
            "//\n"
            "// The landing page's hero tiles, copied into public/hero/ and resized.\n"
            "// Hotlinking them from Amazon's CDN cost 25 third-party requests on\n"
            "// first paint and left the top rows still arriving after six seconds.\n"
            "// Re-run the script to refresh the wall from recent scans.\n"
            "export const HERO_IMAGES: string[] = [\n"
        )
        for n in saved:
            fh.write(f'  "/hero/{n}",\n')
        fh.write("];\n")

    print(f"\n{len(saved)} tiles, {total/1024:.0f}KB total")
    print(f"  -> public/hero/")
    print(f"  -> src/lib/heroImages.ts")
    return 0 if saved else 1


if __name__ == "__main__":
    raise SystemExit(main())
